# commend line: main.py --work-dir work_dir/voc/resnet50 --config ./config/voc/resnet50_cam_m.yaml --device 0

base_lr: 0.01
batch_size: 32
config: ./config/voc/resnet50_cam_m.yaml
device:
- 0
feeder: feeders.voc.VOC12ClassificationDataset
ignore_weights: []
log_interval: 10
loss: MultilabelLoss
model: model.ResNet50_cam_m.resnet50
model_args:
  num_classes: 20
model_saved_name: resnet50
num_classes: 100
num_epoch: 50
num_worker: 8
optimizer: SGD
save_epoch: 30
save_interval: 10
scheduler: StepLR
seed: 2023
start_epoch: 0
test_batch_size: 32
test_feeder_args:
  crop_size: 512
  img_name_list_path: ./data/VOCdevkit/voc12/val.txt
  voc12_root: ./data/VOCdevkit/VOC2012
train_feeder_args:
  crop_method: random
  crop_size: 512
  hor_flip: true
  img_name_list_path: ./data/VOCdevkit/voc12/train_aug.txt
  resize_long:
  - 320
  - 640
  voc12_root: ./data/VOCdevkit/VOC2012
weight_decay: 0.0001
weights: ResNet_ImageNet
work_dir: work_dir/voc/resnet50
