results_dir: ./work_dir/voc/resnet50_cam_m

weights : work_dir/voc/resnet50:11

# feeder
num_worker : 8

feeder: feeders.voc.VOC12ClassificationDatasetBASE
train_feeder_args:
  img_name_list_path : ./data/VOCdevkit/voc12/train_aug.txt
  voc12_root: ./data/VOCdevkit/VOC2012
  scales : [1.0, 0.5, 1.5, 2.0]

test_feeder_args:
  img_name_list_path : ./data/VOCdevkit/voc12/val.txt
  voc12_root: ./data/VOCdevkit/VOC2012

# feeder: feeders.voc.VOC12ClassificationDatasetMSF
# train_feeder_args:
#   img_name_list_path : ./data/VOCdevkit/voc12/train_aug.txt
#   voc12_root: ./data/VOCdevkit/VOC2012
#   scales : [1.0, 0.5, 1.5, 2.0]

# test_feeder_args:
#   img_name_list_path : ./data/VOCdevkit/voc12/val.txt
#   voc12_root: ./data/VOCdevkit/VOC2012
#   scales : [1.0, 0.5, 1.5, 2.0]

# model
model: model.ResNet50_cam_m.resnet50
model_args:
  num_classes: 20

# training
device: [0,1]
batch_size: 1


# random seed
seed: 2023

